### ISSUE TITLE
Korean text is broken

### ISSUE THREAD

**Issue by jnhyeon** [Aggregate-Genius/periscope2#61]
I use the bs4Dash package to develop web apps.
I'm very excited to discover periscope2, a package based on bs4Dash.

However, when you enter Korean text in menuItem() of sidebarMenu, the letters appear garbled.

sidebar_menu <-  sidebarMenu(
  sidebarHeader('BP Reporting'),
  menuItem(
    '한글', # Korean text
    tabName = 'bp_report_eda',
    icon    = icon('building')
  )
)

Please provide a solution.

**Comment by agenius-mohammed-ali** [comment]
Thank you @jnhyeon for using periscope2
I used your text inside periscope2 example and it is working fine
![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/3f2c8f9c-2e87-44b5-a703-96dd5502aa89)
The used environment is R 4.2.3 and periscope 0.2.2
The code is can be found in the example app:
```r
sidebar_menu <-  sidebarMenu(
    sidebarHeader("Periscope2 Features"),
    menuItem(
        "한글",
        tabName = "application_setup",
        icon    = icon("building")
    ),
    menuItem(
        "Periscope2 Modules",
        tabName = "periscope_modules",
        icon    = icon("cubes")
    ), ...
```
