### ISSUE TITLE
sidebar menu appears obscured

### ISSUE THREAD

**Issue by jnhyeon** [Aggregate-Genius/periscope2#72]
Thank you for creating and sharing this wonderful package.

I am developing various data analysis applications using bs4Dash at my company.
In the future, we plan to develop using periscope2.

During testing, I found that the sidebar menu appeared obscured.
Please check.

![image](https://github.com/Aggregate-Genius/periscope2/assets/3360511/721830a0-b3f5-42f8-addc-6d44b2fd1858)

**Comment by cb4ds** [comment]
Thank you for letting us know - please provide the SessionInfo() output if possible

**Comment by jnhyeon** [comment]
The contents of sessionInfo() are as follows.
Thank you

> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2019 x64 (build 17763)

Matrix products: default


locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   
[3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

time zone: Asia/Seoul
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2    tools_4.3.2       rstudioapi_0.15.0 renv_1.0.5

**Comment by agenius-mohammed-ali** [comment]
Thanks @jnhyeon for using periscope2 - what version of periscope2 you are using? did you made any modifications to the sample app? thank you

**Comment by jnhyeon** [comment]
The version of 'periscope2' is 0.2.3, and the sample app has not been modified.
Thank you

![image](https://github.com/Aggregate-Genius/periscope2/assets/3360511/5058e2d2-66b0-4957-8e78-ac1be342b4e3)

**Comment by agenius-mohammed-ali** [comment]
Reproduced the issue using small window successfully
![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/cea8afb6-19fb-409a-a250-080e97fefbe0)
@jnhyeon - a fix is under development and it will be addressed in next package release soon. Thank you

**Comment by agenius-mohammed-ali** [comment]
@jnhyeon - kindly be informed that:
- this issue can be resolved via generated app  `/www/css/custom.css` file
- This file provides classes to control different app UI css advanced properties
- One of this UI parts is the left sidebar which can be controlled via `aside#sidebarId` css class
- Current default configuration (which will be changed in future releases) has a low z-index
![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/8ee46887-0fe0-4bdf-8aec-56a78f28af34)
- Resolving above issue can be resolved issue by removing `z-index: 0!important;` as shown below

![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/d02364a9-7f80-4126-b9c7-675bb6d27162)
![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/b26841dd-8859-4888-9ec6-8b4b9e72a3f6)
![image](https://github.com/Aggregate-Genius/periscope2/assets/76930969/cb513b98-f441-4757-8cc7-990ee4b35f83)
- Please let me know if this resolves your issue or you have another inquiry. 
Thank you

**Comment by jnhyeon** [comment]
The issue was resolved using the method you provided.
I hope to see more functional modules added to periscope2.
Thank you 👍

**Comment by agenius-mohammed-ali** [comment]
Glad to hear that. Please if you have any suggestions for modules or enhancements you can open an enhancement issue. Thank you
